### ISSUE TITLE
Update DNS entry

### ISSUE THREAD

**Issue by rvosa** [Pfern/OSODOS#15]
i.e. point osodos.org to https://pfern.github.io/OSODOS/gitbook/

**Comment by Pfern** [comment]
And https://github.com/Pfern/OSODOS should mention http://osodos.org 
and the book at https://pfern.github.io/OSODOS/gitbook/

osodos.org is blocked at IGC because it is a new website. I filed-in a request to Fortinet to unblock it.

Rutger, will you please put some minimal content there?

**Comment by rvosa** [comment]
Done:
- the DNS entry is set to the root of the gitbook
- the README.md on the git project as a whole knows about this as of 44d3cbe7cc2ee0f0e228ae8428b2f563c6922d8b
