### ISSUE TITLE
Lime

### ISSUE THREAD

**Issue by Pfern** [Pfern/OSODOS#18]
Announcing lime - Explaining the predictions of black-box models
http://www.data-imaginist.com/2017/Announcing-lime/

I think that this make big dents in model assessment and data science in general.

**Comment by rvosa** [comment]
Is this an issue to resolve? I don't think our progress will be derailed up if I just close this :)

**Comment by Pfern** [comment]
I agree. Should not be in our way at tis stage. This kind of methodology makes sense in open science and is likely to become important. Maybe too early to refer to it in OSODOS.
