### ISSUE TITLE
Choose cover image

### ISSUE THREAD

**Issue by rvosa** [Pfern/OSODOS#19]
- [x] add cover art bitmaps to the repo
- [x] combine them with institutional logos (maybe link to separate files in the same document?)
- [x] lay out rest of the cover page

**Comment by Pfern** [comment]
![osodos_cover_75dpi](https://user-images.githubusercontent.com/354516/30997011-20c2435e-a4c5-11e7-8c48-497861c49757.png)

Attempt 75dpi merged image

**Comment by Pfern** [comment]
![osodos_cover_a](https://user-images.githubusercontent.com/354516/30997061-8319da12-a4c5-11e7-8aa4-43ac21c15031.png)

Variant, author names in white, 120dpi, merged image

**Comment by Pfern** [comment]
Image usage rights, cleared

https://commons.wikimedia.org/wiki/File:The_Scallop_sculpture_of_Aldeburgh,_Suffolk,_East_Anglia,_England.jpg

https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia

**Comment by Pfern** [comment]
Maybe this other picture
https://upload.wikimedia.org/wikipedia/commons/a/a7/The_Scallop%2C_Maggi_Hambling%2C_Aldeburgh.jpg

**Comment by rvosa** [comment]
It's a beautiful image, especially the last one you dug up. Can we connect the message of the sculpture with our gitbook? Does it make sense to insert text into the bitmap, or is it better to use the image as is with the title/authors/etc. above and below it (from the perspective of crawlers and indexers being able to parse text)?

**Comment by Pfern** [comment]
"I hear those voices that will not be drowned" is from Peter Grimes (opera). I think that it was a political meaning, but I do not see a reason to make the explicit connection here. Maybe the readers can form their own.
Bitmap with embedded text. Crawlers and indexers will work all the same as we only repeat what is also written as text on the same page. But we could also opt for an image without text as you have already done on the website.Please choose.  We should put the picture references visible anyway.

**Comment by Pfern** [comment]
Let us use the second image 
docs/images/scallop.png  and make it show in the e-book as well. 
We could add a caption like
"Maggi Hambling,  **The Scallop** sculpture north of Aldeburgh, Suffolk, East Anglia, England." 

For the purpose of publicising the e-book in social media, here is a bitmap with the title, sub-title and authors 
https://github.com/Pfern/OSODOS/blob/master/docs/images/OSODOS_splash.png

**Comment by rvosa** [comment]
What do you think of this? https://raw.githubusercontent.com/Pfern/OSODOS/master/docs/images/OSODOS_splash1.png

**Comment by rvosa** [comment]
Also, are we entitled to use the Elixir logo?

**Comment by Pfern** [comment]
I think it is very good and eye catching, more than mine.
I propose that we make a second copy to use as a poster and in social media, where we add the URL http://osodos.org and possibly a QR code for the book. What do you think?

**Comment by rvosa** [comment]
https://raw.githubusercontent.com/Pfern/OSODOS/master/docs/images/OSODOS_splash1_QR.png
