### ISSUE TITLE
Preparation for doi version 1.0

### ISSUE THREAD

**Issue by Pfern** [Pfern/OSODOS#21]
It would be nice to do this quickly, we are entering the Open Access week.

Read;
https://blogs.openaire.eu/?p=2010

**Comment by rvosa** [comment]
I know how to do this - I've done it for some other repos this week.
However, not being the admin I can't do this for the OSODOS repo. I wonder
if you can make me the co-admin on github? I hope/suspect that will make it
so that OSODOS shows up in my Zenodo listing of DOI candidates, and then
it's just a matter of flipping the switch and creating a release.

**Comment by Pfern** [comment]
I agree, but how can I do that? I remember that we tried before but the option of co-administration was not there. Actually, see this question in StackOverflow:
https://stackoverflow.com/questions/8015579/add-another-user-to-project-owners-in-github
At this stage the pull requests are not so many and that would do.
It is also a flip of the switch for me, so the issue is to agree on "when". The code is there.

**Comment by rvosa** [comment]
Then you will have to do it:

- go to Zenodo.org
- log in via github
- in the top-right pull down menu, choose the github option
- in the listing of your repositories, flick the switch for OSODOS
- git tag a release (I propose v0.1.0, with semantic versioning)
- push the tags
- click on the OSODOS repository within the Zenodo interface
- choose the 'make release' option
- this takes you to github, where you make a release associated with the
tagged version
- Zenodo issues the DOI

From this point onwards, making new releases will result in additional DOIs

**Comment by Pfern** [comment]
Please check my last updates (ROADMAP) and the cover image issue

**Comment by Pfern** [comment]
Issued v0.1.0 as a pre-release and v1.0.0 as the Initial release.

Zenodo looks happy    https://zenodo.org/badge/latestdoi/73615184

We might have cleaned-up some files that we do not really need. Pending, for the next release.

BADGE:     https://zenodo.org/badge/73615184.svg

**Comment by Pfern** [comment]
QR code for http://osodos.org
![static_qr_code_without_logo](https://user-images.githubusercontent.com/354516/31680705-02ca1afa-b36d-11e7-844e-3f17d7fa5f90.jpg)

**Comment by rvosa** [comment]
Excellent. I propose that we now start a table on the front matter page to keep track of the versions, with release date, and DOI.

**Comment by matuskalas** [comment]
Congrats with the release, and I'm glad it worked out with the DOIs!

Here is an example of including them into the README file: https://github.com/edamontology/edamontology/blob/master/README.md
Code:

```
__DOI representing all stable versions, resolving to the latest__: [![10.5281/zenodo.822690](https://zenodo.org/badge/DOI/10.5281/zenodo.822690.svg)](https://doi.org/10.5281/zenodo.822690)

__DOI of the latest stable version__: [![Latest DOI](https://zenodo.org/badge/20960594.svg)](https://zenodo.org/badge/latestdoi/20960594)

__Current status of the 'master' development file__: [![Build status](https://travis-ci.org/edamontology/edamontology.svg?branch=master)](https://travis-ci.org/edamontology/edamontology)

Twitter: [@edamontology](http://twitter.com/edamontology) ([follow](https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fgithub.com%2Fedamontology%2Fedamontology&region=follow_link&screen_name=edamontology&tw_p=followbutton)).

# What is EDAM?
```

And here is the list of all releases generated by GitHub (no need for a custom-made table): https://github.com/edamontology/edamontology/releases
The DOI has been added post release.
Code:
```
# EDAM\_1.18.owl  [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.822691.svg)](https://doi.org/10.5281/zenodo.822691)
See [changelog-detailed.md](https://github.com/edamontology/edamontology/blob/master/changelog-detailed.md) for additions, deprecations, and changes in relations between concepts.

EDAM\_1.18 includes:

* EDAM is now available in 2 additional formats: CSV and TSV
  * http://edamontology.org/EDAM.csv is optimised for use in spreadsheet apps (_e.g._ Excel)
  * http://edamontology.org/EDAM.tsv is optimised for scripting
  * Available for EDAM versions 1.16 and newer
  * More details in [#268](https://github.com/edamontology/edamontology/issues/268)
* EDAM versions are now graphically browsable online in WebProtégé
  * Free registration required
  * Available for EDAM versions 1.16 and newer, including the unstable [development version](http://webprotege.stanford.edu/#projects/4befad5f-f27b-430c-a07d-fcf635093169/edit/Classes)
  * Links to the different EDAM versions are at http://edamontology.org/page#Viewing and in [README.md](README.md)
* EDAM releases now have DOIs
  * DOI representing all released versions, resolving to the latest: [10.5281/zenodo.822690](https://doi.org/10.5281/zenodo.822690)
  * DOI of EDAM version 1.18: [10.5281/zenodo.822691](https://doi.org/10.5281/zenodo.822691)
* various refactoring including concepts deprecations within the Operation sub-ontology to make this simpler and improve usability
* new attribute to provide tips _e.g._ in bio.tools UI indicating "organisational concepts", _i.e._ higher-level concepts which primarily structure the hierarchy and are not normally recommended for annotation
* LICENSE added to the EDAM repo (in _.md_ and plain text) for immediate recognition
```

It also appears that the original release notes may become the abstract of the Zenodo record, as in here: https://doi.org/10.5281/zenodo.822690

**Comment by Pfern** [comment]
Thanks for this, Matus

We will consider doing it. It seems to add some value to the release process

**Comment by rvosa** [comment]
I've made a table that we can add release versions to:
https://github.com/Pfern/OSODOS/blob/master/docs/README.md
