### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by rvosa** [Pfern/OSODOS#22]
...do we get them via github pages? Or do we need to insert a google analytics widget?

**Comment by Pfern** [comment]
We need to investigate that. It seems logical.

**Comment by Pfern** [comment]
Maybe this is better https://github.com/GitbookIO/plugin-ga

**Comment by rvosa** [comment]
Very nice, let's do that.

**Comment by rvosa** [comment]
Realtime analytics are coming in: there are now 7 people reading the e-book. I added you as admin to the platform, you should have received an invitation to your gmail.
