### ISSUE TITLE
Steps to making a website

### ISSUE THREAD

**Issue by rvosa** [Pfern/OSODOS#5]
Assuming the prose is finished, here's what needs to happen:
- [ ] make a `gh-pages` branch
- [ ] rename all the README.md to index.md
- [ ] add supporting files from https://github.com/NESCent/community-and-code/tree/gh-pages
- [ ] adjust supporting files: update navigation, add logos

**Comment by Pfern** [comment]
We need to assess the advantages of making separate branches, in principle it makes sense to have one for the Website, and a different (?) one for the e-book.
