### ISSUE TITLE
Options for diffusion of these contents

### ISSUE THREAD

**Issue by rvosa** [Pfern/OSODOS#8]
Several opportunities are presenting themselves for diffusing these contents. To wit:

- [x] As a standalone e-book advertised via the participating institutions, i.e. Gulbenkian & Naturalis
- [ ] [ELIXIR](https://www.elixir-europe.org/) via [GOBLET](http://www.mygoblet.org/)
- [x] The MSc course [Methods of Biodiversity Analysis](https://studiegids.leidenuniv.nl/courses/show/56721/Methods-in-Biodiversity-Analysis)
- [x] The [Open Science MOOC](https://opensciencemooc.eu/)
- [x] [Foster](https://www.fosteropenscience.eu/) open science [sprint](https://www.fosteropenscience.eu/content/call-open-science-trainers-%E2%80%93-share-your-experiences-and-help-write-book) (12-15 February, Hannover)

**Comment by rvosa** [comment]
@Pfern, what was the initiative again to do a 4-day writing sprint on open science?

**Comment by Pfern** [comment]
Foster    https://www.fosteropenscience.eu/

Book Sprint:  12-15 February in Hanover
https://www.fosteropenscience.eu/content/call-open-science-trainers-%E2%80%93-share-your-experiences-and-help-write-book

**Comment by rvosa** [comment]
I think we are moving fairly well on all these that are checked - how is the ELIXIR link? Also, should we work the logo into our cover art?
